{{- if .Values.deployment.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "oke-gateway-api-controller.fullname" . }}-role
  labels:
    {{- include "oke-gateway-api-controller.labels" . | nindent 4 }}
rules:
# Permissions to watch and update Gateway API resources
- apiGroups: ["gateway.networking.k8s.io"]
  resources: ["gatewayclasses", "gateways", "httproutes", "grpcroutes", "tcproutes", "udproutes", "tlsroutes", "backendtlspolicies", "listenersets", "referencegrants"]
  verbs: ["get", "list", "watch", "update", "patch"] # Read access + update/patch for finalizers/annotations
- apiGroups: ["gateway.networking.k8s.io"]
  resources: ["gatewayclasses/status", "gateways/status", "httproutes/status", "grpcroutes/status", "tcproutes/status", "udproutes/status", "tlsroutes/status", "backendtlspolicies/status", "listenersets/status"]
  verbs: ["update", "patch"] # Update status
# Permissions to read necessary core resources for OCI LB configuration
- apiGroups: [""]
  resources: ["services", "endpoints", "secrets", "configmaps", "nodes", "namespaces"]
  verbs: ["get", "list", "watch"] # Read-only access
# Permissions for leader election
- apiGroups: ["coordination.k8s.io"]
  resources: ["leases"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"] 
# Permission to get endpointslices
- apiGroups: ["discovery.k8s.io"]
  resources: ["endpointslices"]
  verbs: ["get", "list", "watch"]
# Permission to list own configs
- apiGroups: ["oke-gateway-api.gemyago.github.io"]
  resources: ["gateway-configs"]
  verbs: ["get", "list", "watch"]
{{- end }}
