// Code generated by mockery. DO NOT EDIT.

//go:build !release

package app

import (
	context "context"

	corev1 "k8s.io/api/core/v1"

	mock "github.com/stretchr/testify/mock"

	reconcile "sigs.k8s.io/controller-runtime/pkg/reconcile"

	v1 "sigs.k8s.io/gateway-api/apis/v1"
)

// MockhttpRouteModel is an autogenerated mock type for the httpRouteModel type
type MockhttpRouteModel struct {
	mock.Mock
}

type MockhttpRouteModel_Expecter struct {
	mock *mock.Mock
}

func (_m *MockhttpRouteModel) EXPECT() *MockhttpRouteModel_Expecter {
	return &MockhttpRouteModel_Expecter{mock: &_m.Mock}
}

// acceptRoute provides a mock function with given fields: ctx, routeDetails
func (_m *MockhttpRouteModel) acceptRoute(ctx context.Context, routeDetails resolvedRouteDetails) (*v1.HTTPRoute, error) {
	hasExpectation := false
	for _, expectedCall := range _m.ExpectedCalls {
		if expectedCall.Method == "acceptRoute" {
			hasExpectation = true
			break
		}
	}
	if !hasExpectation {
		return &routeDetails.httpRoute, nil
	}

	ret := _m.Called(ctx, routeDetails)

	if len(ret) == 0 {
		panic("no return value specified for acceptRoute")
	}

	var r0 *v1.HTTPRoute
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, resolvedRouteDetails) (*v1.HTTPRoute, error)); ok {
		return rf(ctx, routeDetails)
	}
	if rf, ok := ret.Get(0).(func(context.Context, resolvedRouteDetails) *v1.HTTPRoute); ok {
		r0 = rf(ctx, routeDetails)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.HTTPRoute)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, resolvedRouteDetails) error); ok {
		r1 = rf(ctx, routeDetails)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockhttpRouteModel_acceptRoute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'acceptRoute'
type MockhttpRouteModel_acceptRoute_Call struct {
	*mock.Call
}

// acceptRoute is a helper method to define mock.On call
//   - ctx context.Context
//   - routeDetails resolvedRouteDetails
func (_e *MockhttpRouteModel_Expecter) acceptRoute(ctx interface{}, routeDetails interface{}) *MockhttpRouteModel_acceptRoute_Call {
	return &MockhttpRouteModel_acceptRoute_Call{Call: _e.mock.On("acceptRoute", ctx, routeDetails)}
}

func (_c *MockhttpRouteModel_acceptRoute_Call) Run(run func(ctx context.Context, routeDetails resolvedRouteDetails)) *MockhttpRouteModel_acceptRoute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(resolvedRouteDetails))
	})
	return _c
}

func (_c *MockhttpRouteModel_acceptRoute_Call) Return(_a0 *v1.HTTPRoute, _a1 error) *MockhttpRouteModel_acceptRoute_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockhttpRouteModel_acceptRoute_Call) RunAndReturn(run func(context.Context, resolvedRouteDetails) (*v1.HTTPRoute, error)) *MockhttpRouteModel_acceptRoute_Call {
	_c.Call.Return(run)
	return _c
}

// deprovisionRoute provides a mock function with given fields: ctx, params
func (_m *MockhttpRouteModel) deprovisionRoute(ctx context.Context, params deprovisionRouteParams) error {
	ret := _m.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for deprovisionRoute")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, deprovisionRouteParams) error); ok {
		r0 = rf(ctx, params)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockhttpRouteModel_deprovisionRoute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'deprovisionRoute'
type MockhttpRouteModel_deprovisionRoute_Call struct {
	*mock.Call
}

// deprovisionRoute is a helper method to define mock.On call
//   - ctx context.Context
//   - params deprovisionRouteParams
func (_e *MockhttpRouteModel_Expecter) deprovisionRoute(ctx interface{}, params interface{}) *MockhttpRouteModel_deprovisionRoute_Call {
	return &MockhttpRouteModel_deprovisionRoute_Call{Call: _e.mock.On("deprovisionRoute", ctx, params)}
}

func (_c *MockhttpRouteModel_deprovisionRoute_Call) Run(run func(ctx context.Context, params deprovisionRouteParams)) *MockhttpRouteModel_deprovisionRoute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(deprovisionRouteParams))
	})
	return _c
}

func (_c *MockhttpRouteModel_deprovisionRoute_Call) Return(_a0 error) *MockhttpRouteModel_deprovisionRoute_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockhttpRouteModel_deprovisionRoute_Call) RunAndReturn(run func(context.Context, deprovisionRouteParams) error) *MockhttpRouteModel_deprovisionRoute_Call {
	_c.Call.Return(run)
	return _c
}

// isProgrammingRequired provides a mock function with given fields: details
func (_m *MockhttpRouteModel) isProgrammingRequired(details resolvedRouteDetails) (bool, error) {
	ret := _m.Called(details)

	if len(ret) == 0 {
		panic("no return value specified for isProgrammingRequired")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(resolvedRouteDetails) (bool, error)); ok {
		return rf(details)
	}
	if rf, ok := ret.Get(0).(func(resolvedRouteDetails) bool); ok {
		r0 = rf(details)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(resolvedRouteDetails) error); ok {
		r1 = rf(details)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockhttpRouteModel_isProgrammingRequired_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'isProgrammingRequired'
type MockhttpRouteModel_isProgrammingRequired_Call struct {
	*mock.Call
}

// isProgrammingRequired is a helper method to define mock.On call
//   - details resolvedRouteDetails
func (_e *MockhttpRouteModel_Expecter) isProgrammingRequired(details interface{}) *MockhttpRouteModel_isProgrammingRequired_Call {
	return &MockhttpRouteModel_isProgrammingRequired_Call{Call: _e.mock.On("isProgrammingRequired", details)}
}

func (_c *MockhttpRouteModel_isProgrammingRequired_Call) Run(run func(details resolvedRouteDetails)) *MockhttpRouteModel_isProgrammingRequired_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(resolvedRouteDetails))
	})
	return _c
}

func (_c *MockhttpRouteModel_isProgrammingRequired_Call) Return(_a0 bool, _a1 error) *MockhttpRouteModel_isProgrammingRequired_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockhttpRouteModel_isProgrammingRequired_Call) RunAndReturn(run func(resolvedRouteDetails) (bool, error)) *MockhttpRouteModel_isProgrammingRequired_Call {
	_c.Call.Return(run)
	return _c
}

// programRoute provides a mock function with given fields: ctx, params
func (_m *MockhttpRouteModel) programRoute(ctx context.Context, params programRouteParams) (programRouteResult, error) {
	ret := _m.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for programRoute")
	}

	var r0 programRouteResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, programRouteParams) (programRouteResult, error)); ok {
		return rf(ctx, params)
	}
	if rf, ok := ret.Get(0).(func(context.Context, programRouteParams) programRouteResult); ok {
		r0 = rf(ctx, params)
	} else {
		r0 = ret.Get(0).(programRouteResult)
	}

	if rf, ok := ret.Get(1).(func(context.Context, programRouteParams) error); ok {
		r1 = rf(ctx, params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockhttpRouteModel_programRoute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'programRoute'
type MockhttpRouteModel_programRoute_Call struct {
	*mock.Call
}

// programRoute is a helper method to define mock.On call
//   - ctx context.Context
//   - params programRouteParams
func (_e *MockhttpRouteModel_Expecter) programRoute(ctx interface{}, params interface{}) *MockhttpRouteModel_programRoute_Call {
	return &MockhttpRouteModel_programRoute_Call{Call: _e.mock.On("programRoute", ctx, params)}
}

func (_c *MockhttpRouteModel_programRoute_Call) Run(run func(ctx context.Context, params programRouteParams)) *MockhttpRouteModel_programRoute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(programRouteParams))
	})
	return _c
}

func (_c *MockhttpRouteModel_programRoute_Call) Return(_a0 programRouteResult, _a1 error) *MockhttpRouteModel_programRoute_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockhttpRouteModel_programRoute_Call) RunAndReturn(run func(context.Context, programRouteParams) (programRouteResult, error)) *MockhttpRouteModel_programRoute_Call {
	_c.Call.Return(run)
	return _c
}

// resolveBackendRefs provides a mock function with given fields: ctx, params
func (_m *MockhttpRouteModel) resolveBackendRefs(ctx context.Context, params resolveBackendRefsParams) (map[string]corev1.Service, error) {
	ret := _m.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for resolveBackendRefs")
	}

	var r0 map[string]corev1.Service
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, resolveBackendRefsParams) (map[string]corev1.Service, error)); ok {
		return rf(ctx, params)
	}
	if rf, ok := ret.Get(0).(func(context.Context, resolveBackendRefsParams) map[string]corev1.Service); ok {
		r0 = rf(ctx, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]corev1.Service)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, resolveBackendRefsParams) error); ok {
		r1 = rf(ctx, params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockhttpRouteModel_resolveBackendRefs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'resolveBackendRefs'
type MockhttpRouteModel_resolveBackendRefs_Call struct {
	*mock.Call
}

// resolveBackendRefs is a helper method to define mock.On call
//   - ctx context.Context
//   - params resolveBackendRefsParams
func (_e *MockhttpRouteModel_Expecter) resolveBackendRefs(ctx interface{}, params interface{}) *MockhttpRouteModel_resolveBackendRefs_Call {
	return &MockhttpRouteModel_resolveBackendRefs_Call{Call: _e.mock.On("resolveBackendRefs", ctx, params)}
}

func (_c *MockhttpRouteModel_resolveBackendRefs_Call) Run(run func(ctx context.Context, params resolveBackendRefsParams)) *MockhttpRouteModel_resolveBackendRefs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(resolveBackendRefsParams))
	})
	return _c
}

func (_c *MockhttpRouteModel_resolveBackendRefs_Call) Return(_a0 map[string]corev1.Service, _a1 error) *MockhttpRouteModel_resolveBackendRefs_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockhttpRouteModel_resolveBackendRefs_Call) RunAndReturn(run func(context.Context, resolveBackendRefsParams) (map[string]corev1.Service, error)) *MockhttpRouteModel_resolveBackendRefs_Call {
	_c.Call.Return(run)
	return _c
}

// resolveRequest provides a mock function with given fields: ctx, req
func (_m *MockhttpRouteModel) resolveRequest(ctx context.Context, req reconcile.Request) (map[routeParentResultKey]resolvedRouteDetails, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for resolveRequest")
	}

	var r0 map[routeParentResultKey]resolvedRouteDetails
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, reconcile.Request) (map[routeParentResultKey]resolvedRouteDetails, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, reconcile.Request) map[routeParentResultKey]resolvedRouteDetails); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[routeParentResultKey]resolvedRouteDetails)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, reconcile.Request) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockhttpRouteModel_resolveRequest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'resolveRequest'
type MockhttpRouteModel_resolveRequest_Call struct {
	*mock.Call
}

// resolveRequest is a helper method to define mock.On call
//   - ctx context.Context
//   - req reconcile.Request
func (_e *MockhttpRouteModel_Expecter) resolveRequest(ctx interface{}, req interface{}) *MockhttpRouteModel_resolveRequest_Call {
	return &MockhttpRouteModel_resolveRequest_Call{Call: _e.mock.On("resolveRequest", ctx, req)}
}

func (_c *MockhttpRouteModel_resolveRequest_Call) Run(run func(ctx context.Context, req reconcile.Request)) *MockhttpRouteModel_resolveRequest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(reconcile.Request))
	})
	return _c
}

func (_c *MockhttpRouteModel_resolveRequest_Call) Return(_a0 map[routeParentResultKey]resolvedRouteDetails, _a1 error) *MockhttpRouteModel_resolveRequest_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockhttpRouteModel_resolveRequest_Call) RunAndReturn(run func(context.Context, reconcile.Request) (map[routeParentResultKey]resolvedRouteDetails, error)) *MockhttpRouteModel_resolveRequest_Call {
	_c.Call.Return(run)
	return _c
}

// setProgrammed provides a mock function with given fields: ctx, params
func (_m *MockhttpRouteModel) setProgrammed(ctx context.Context, params setProgrammedParams) error {
	ret := _m.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for setProgrammed")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, setProgrammedParams) error); ok {
		r0 = rf(ctx, params)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockhttpRouteModel_setProgrammed_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'setProgrammed'
type MockhttpRouteModel_setProgrammed_Call struct {
	*mock.Call
}

// setProgrammed is a helper method to define mock.On call
//   - ctx context.Context
//   - params setProgrammedParams
func (_e *MockhttpRouteModel_Expecter) setProgrammed(ctx interface{}, params interface{}) *MockhttpRouteModel_setProgrammed_Call {
	return &MockhttpRouteModel_setProgrammed_Call{Call: _e.mock.On("setProgrammed", ctx, params)}
}

func (_c *MockhttpRouteModel_setProgrammed_Call) Run(run func(ctx context.Context, params setProgrammedParams)) *MockhttpRouteModel_setProgrammed_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(setProgrammedParams))
	})
	return _c
}

func (_c *MockhttpRouteModel_setProgrammed_Call) Return(_a0 error) *MockhttpRouteModel_setProgrammed_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockhttpRouteModel_setProgrammed_Call) RunAndReturn(run func(context.Context, setProgrammedParams) error) *MockhttpRouteModel_setProgrammed_Call {
	_c.Call.Return(run)
	return _c
}

// setPending provides a mock function with given fields: ctx, params
func (_m *MockhttpRouteModel) setPending(ctx context.Context, params setProgrammedParams) error {
	ret := _m.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for setPending")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, setProgrammedParams) error); ok {
		r0 = rf(ctx, params)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockhttpRouteModel_setPending_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'setPending'
type MockhttpRouteModel_setPending_Call struct {
	*mock.Call
}

// setPending is a helper method to define mock.On call
//   - ctx context.Context
//   - params setProgrammedParams
func (_e *MockhttpRouteModel_Expecter) setPending(ctx interface{}, params interface{}) *MockhttpRouteModel_setPending_Call {
	return &MockhttpRouteModel_setPending_Call{Call: _e.mock.On("setPending", ctx, params)}
}

func (_c *MockhttpRouteModel_setPending_Call) Run(run func(ctx context.Context, params setProgrammedParams)) *MockhttpRouteModel_setPending_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(setProgrammedParams))
	})
	return _c
}

func (_c *MockhttpRouteModel_setPending_Call) Return(_a0 error) *MockhttpRouteModel_setPending_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockhttpRouteModel_setPending_Call) RunAndReturn(run func(context.Context, setProgrammedParams) error) *MockhttpRouteModel_setPending_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockhttpRouteModel creates a new instance of MockhttpRouteModel. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockhttpRouteModel(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockhttpRouteModel {
	mock := &MockhttpRouteModel{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
