// Code generated by mockery. DO NOT EDIT.

//go:build !release

package app

import (
	context "context"

	loadbalancer "github.com/oracle/oci-go-sdk/v65/loadbalancer"
	mock "github.com/stretchr/testify/mock"
)

// MockociLoadBalancerModel is an autogenerated mock type for the ociLoadBalancerModel type
type MockociLoadBalancerModel struct {
	mock.Mock
}

type MockociLoadBalancerModel_Expecter struct {
	mock *mock.Mock
}

func (_m *MockociLoadBalancerModel) EXPECT() *MockociLoadBalancerModel_Expecter {
	return &MockociLoadBalancerModel_Expecter{mock: &_m.Mock}
}

// commitRoutingPolicy provides a mock function with given fields: ctx, params
func (_m *MockociLoadBalancerModel) commitRoutingPolicy(ctx context.Context, params commitRoutingPolicyParams) error {
	ret := _m.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for commitRoutingPolicy")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, commitRoutingPolicyParams) error); ok {
		r0 = rf(ctx, params)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockociLoadBalancerModel_commitRoutingPolicy_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'commitRoutingPolicy'
type MockociLoadBalancerModel_commitRoutingPolicy_Call struct {
	*mock.Call
}

// commitRoutingPolicy is a helper method to define mock.On call
//   - ctx context.Context
//   - params commitRoutingPolicyParams
func (_e *MockociLoadBalancerModel_Expecter) commitRoutingPolicy(ctx interface{}, params interface{}) *MockociLoadBalancerModel_commitRoutingPolicy_Call {
	return &MockociLoadBalancerModel_commitRoutingPolicy_Call{Call: _e.mock.On("commitRoutingPolicy", ctx, params)}
}

func (_c *MockociLoadBalancerModel_commitRoutingPolicy_Call) Run(run func(ctx context.Context, params commitRoutingPolicyParams)) *MockociLoadBalancerModel_commitRoutingPolicy_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(commitRoutingPolicyParams))
	})
	return _c
}

func (_c *MockociLoadBalancerModel_commitRoutingPolicy_Call) Return(_a0 error) *MockociLoadBalancerModel_commitRoutingPolicy_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockociLoadBalancerModel_commitRoutingPolicy_Call) RunAndReturn(run func(context.Context, commitRoutingPolicyParams) error) *MockociLoadBalancerModel_commitRoutingPolicy_Call {
	_c.Call.Return(run)
	return _c
}

// deprovisionBackendSet provides a mock function with given fields: ctx, params
func (_m *MockociLoadBalancerModel) deprovisionBackendSet(ctx context.Context, params deprovisionBackendSetParams) error {
	ret := _m.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for deprovisionBackendSet")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, deprovisionBackendSetParams) error); ok {
		r0 = rf(ctx, params)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockociLoadBalancerModel_deprovisionBackendSet_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'deprovisionBackendSet'
type MockociLoadBalancerModel_deprovisionBackendSet_Call struct {
	*mock.Call
}

// deprovisionBackendSet is a helper method to define mock.On call
//   - ctx context.Context
//   - params deprovisionBackendSetParams
func (_e *MockociLoadBalancerModel_Expecter) deprovisionBackendSet(ctx interface{}, params interface{}) *MockociLoadBalancerModel_deprovisionBackendSet_Call {
	return &MockociLoadBalancerModel_deprovisionBackendSet_Call{Call: _e.mock.On("deprovisionBackendSet", ctx, params)}
}

func (_c *MockociLoadBalancerModel_deprovisionBackendSet_Call) Run(run func(ctx context.Context, params deprovisionBackendSetParams)) *MockociLoadBalancerModel_deprovisionBackendSet_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(deprovisionBackendSetParams))
	})
	return _c
}

func (_c *MockociLoadBalancerModel_deprovisionBackendSet_Call) Return(_a0 error) *MockociLoadBalancerModel_deprovisionBackendSet_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockociLoadBalancerModel_deprovisionBackendSet_Call) RunAndReturn(run func(context.Context, deprovisionBackendSetParams) error) *MockociLoadBalancerModel_deprovisionBackendSet_Call {
	_c.Call.Return(run)
	return _c
}

// deprovisionBackendSetByName provides a mock function with given fields: ctx, loadBalancerID, backendSetName
func (_m *MockociLoadBalancerModel) deprovisionBackendSetByName(ctx context.Context, loadBalancerID string, backendSetName string) error {
	ret := _m.Called(ctx, loadBalancerID, backendSetName)

	if len(ret) == 0 {
		panic("no return value specified for deprovisionBackendSetByName")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, loadBalancerID, backendSetName)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockociLoadBalancerModel_deprovisionBackendSetByName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'deprovisionBackendSetByName'
type MockociLoadBalancerModel_deprovisionBackendSetByName_Call struct {
	*mock.Call
}

// deprovisionBackendSetByName is a helper method to define mock.On call
//   - ctx context.Context
//   - loadBalancerID string
//   - backendSetName string
func (_e *MockociLoadBalancerModel_Expecter) deprovisionBackendSetByName(ctx interface{}, loadBalancerID interface{}, backendSetName interface{}) *MockociLoadBalancerModel_deprovisionBackendSetByName_Call {
	return &MockociLoadBalancerModel_deprovisionBackendSetByName_Call{Call: _e.mock.On("deprovisionBackendSetByName", ctx, loadBalancerID, backendSetName)}
}

func (_c *MockociLoadBalancerModel_deprovisionBackendSetByName_Call) Run(run func(ctx context.Context, loadBalancerID string, backendSetName string)) *MockociLoadBalancerModel_deprovisionBackendSetByName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockociLoadBalancerModel_deprovisionBackendSetByName_Call) Return(_a0 error) *MockociLoadBalancerModel_deprovisionBackendSetByName_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockociLoadBalancerModel_deprovisionBackendSetByName_Call) RunAndReturn(run func(context.Context, string, string) error) *MockociLoadBalancerModel_deprovisionBackendSetByName_Call {
	_c.Call.Return(run)
	return _c
}

// ensureHTTP2ListenerProtocol provides a mock function with given fields: ctx, params
func (_m *MockociLoadBalancerModel) ensureHTTP2ListenerProtocol(ctx context.Context, params ensureHTTP2ListenerProtocolParams) error {
	ret := _m.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for ensureHTTP2ListenerProtocol")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, ensureHTTP2ListenerProtocolParams) error); ok {
		r0 = rf(ctx, params)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockociLoadBalancerModel_ensureHTTP2ListenerProtocol_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ensureHTTP2ListenerProtocol'
type MockociLoadBalancerModel_ensureHTTP2ListenerProtocol_Call struct {
	*mock.Call
}

// ensureHTTP2ListenerProtocol is a helper method to define mock.On call
//   - ctx context.Context
//   - params ensureHTTP2ListenerProtocolParams
func (_e *MockociLoadBalancerModel_Expecter) ensureHTTP2ListenerProtocol(ctx interface{}, params interface{}) *MockociLoadBalancerModel_ensureHTTP2ListenerProtocol_Call {
	return &MockociLoadBalancerModel_ensureHTTP2ListenerProtocol_Call{Call: _e.mock.On("ensureHTTP2ListenerProtocol", ctx, params)}
}

func (_c *MockociLoadBalancerModel_ensureHTTP2ListenerProtocol_Call) Run(run func(ctx context.Context, params ensureHTTP2ListenerProtocolParams)) *MockociLoadBalancerModel_ensureHTTP2ListenerProtocol_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(ensureHTTP2ListenerProtocolParams))
	})
	return _c
}

func (_c *MockociLoadBalancerModel_ensureHTTP2ListenerProtocol_Call) Return(_a0 error) *MockociLoadBalancerModel_ensureHTTP2ListenerProtocol_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockociLoadBalancerModel_ensureHTTP2ListenerProtocol_Call) RunAndReturn(run func(context.Context, ensureHTTP2ListenerProtocolParams) error) *MockociLoadBalancerModel_ensureHTTP2ListenerProtocol_Call {
	_c.Call.Return(run)
	return _c
}

// makeRoutingRule provides a mock function with given fields: ctx, params
func (_m *MockociLoadBalancerModel) makeRoutingRule(ctx context.Context, params makeRoutingRuleParams) (loadbalancer.RoutingRule, error) {
	ret := _m.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for makeRoutingRule")
	}

	var r0 loadbalancer.RoutingRule
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, makeRoutingRuleParams) (loadbalancer.RoutingRule, error)); ok {
		return rf(ctx, params)
	}
	if rf, ok := ret.Get(0).(func(context.Context, makeRoutingRuleParams) loadbalancer.RoutingRule); ok {
		r0 = rf(ctx, params)
	} else {
		r0 = ret.Get(0).(loadbalancer.RoutingRule)
	}

	if rf, ok := ret.Get(1).(func(context.Context, makeRoutingRuleParams) error); ok {
		r1 = rf(ctx, params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockociLoadBalancerModel_makeRoutingRule_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'makeRoutingRule'
type MockociLoadBalancerModel_makeRoutingRule_Call struct {
	*mock.Call
}

// makeRoutingRule is a helper method to define mock.On call
//   - ctx context.Context
//   - params makeRoutingRuleParams
func (_e *MockociLoadBalancerModel_Expecter) makeRoutingRule(ctx interface{}, params interface{}) *MockociLoadBalancerModel_makeRoutingRule_Call {
	return &MockociLoadBalancerModel_makeRoutingRule_Call{Call: _e.mock.On("makeRoutingRule", ctx, params)}
}

func (_c *MockociLoadBalancerModel_makeRoutingRule_Call) Run(run func(ctx context.Context, params makeRoutingRuleParams)) *MockociLoadBalancerModel_makeRoutingRule_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(makeRoutingRuleParams))
	})
	return _c
}

func (_c *MockociLoadBalancerModel_makeRoutingRule_Call) Return(_a0 loadbalancer.RoutingRule, _a1 error) *MockociLoadBalancerModel_makeRoutingRule_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockociLoadBalancerModel_makeRoutingRule_Call) RunAndReturn(run func(context.Context, makeRoutingRuleParams) (loadbalancer.RoutingRule, error)) *MockociLoadBalancerModel_makeRoutingRule_Call {
	_c.Call.Return(run)
	return _c
}

// makeGRPCRoutingRule provides a mock function with given fields: ctx, params
func (_m *MockociLoadBalancerModel) makeGRPCRoutingRule(ctx context.Context, params makeGRPCRoutingRuleParams) (loadbalancer.RoutingRule, error) {
	ret := _m.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for makeGRPCRoutingRule")
	}

	var r0 loadbalancer.RoutingRule
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, makeGRPCRoutingRuleParams) (loadbalancer.RoutingRule, error)); ok {
		return rf(ctx, params)
	}
	if rf, ok := ret.Get(0).(func(context.Context, makeGRPCRoutingRuleParams) loadbalancer.RoutingRule); ok {
		r0 = rf(ctx, params)
	} else {
		r0 = ret.Get(0).(loadbalancer.RoutingRule)
	}

	if rf, ok := ret.Get(1).(func(context.Context, makeGRPCRoutingRuleParams) error); ok {
		r1 = rf(ctx, params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockociLoadBalancerModel_makeGRPCRoutingRule_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'makeGRPCRoutingRule'
type MockociLoadBalancerModel_makeGRPCRoutingRule_Call struct {
	*mock.Call
}

// makeGRPCRoutingRule is a helper method to define mock.On call
//   - ctx context.Context
//   - params makeGRPCRoutingRuleParams
func (_e *MockociLoadBalancerModel_Expecter) makeGRPCRoutingRule(ctx interface{}, params interface{}) *MockociLoadBalancerModel_makeGRPCRoutingRule_Call {
	return &MockociLoadBalancerModel_makeGRPCRoutingRule_Call{Call: _e.mock.On("makeGRPCRoutingRule", ctx, params)}
}

func (_c *MockociLoadBalancerModel_makeGRPCRoutingRule_Call) Run(run func(ctx context.Context, params makeGRPCRoutingRuleParams)) *MockociLoadBalancerModel_makeGRPCRoutingRule_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(makeGRPCRoutingRuleParams))
	})
	return _c
}

func (_c *MockociLoadBalancerModel_makeGRPCRoutingRule_Call) Return(_a0 loadbalancer.RoutingRule, _a1 error) *MockociLoadBalancerModel_makeGRPCRoutingRule_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockociLoadBalancerModel_makeGRPCRoutingRule_Call) RunAndReturn(run func(context.Context, makeGRPCRoutingRuleParams) (loadbalancer.RoutingRule, error)) *MockociLoadBalancerModel_makeGRPCRoutingRule_Call {
	_c.Call.Return(run)
	return _c
}

// reconcileBackendSet provides a mock function with given fields: ctx, params
func (_m *MockociLoadBalancerModel) reconcileBackendSet(ctx context.Context, params reconcileBackendSetParams) error {
	ret := _m.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for reconcileBackendSet")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, reconcileBackendSetParams) error); ok {
		r0 = rf(ctx, params)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockociLoadBalancerModel_reconcileBackendSet_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'reconcileBackendSet'
type MockociLoadBalancerModel_reconcileBackendSet_Call struct {
	*mock.Call
}

// reconcileBackendSet is a helper method to define mock.On call
//   - ctx context.Context
//   - params reconcileBackendSetParams
func (_e *MockociLoadBalancerModel_Expecter) reconcileBackendSet(ctx interface{}, params interface{}) *MockociLoadBalancerModel_reconcileBackendSet_Call {
	return &MockociLoadBalancerModel_reconcileBackendSet_Call{Call: _e.mock.On("reconcileBackendSet", ctx, params)}
}

func (_c *MockociLoadBalancerModel_reconcileBackendSet_Call) Run(run func(ctx context.Context, params reconcileBackendSetParams)) *MockociLoadBalancerModel_reconcileBackendSet_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(reconcileBackendSetParams))
	})
	return _c
}

func (_c *MockociLoadBalancerModel_reconcileBackendSet_Call) Return(_a0 error) *MockociLoadBalancerModel_reconcileBackendSet_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockociLoadBalancerModel_reconcileBackendSet_Call) RunAndReturn(run func(context.Context, reconcileBackendSetParams) error) *MockociLoadBalancerModel_reconcileBackendSet_Call {
	_c.Call.Return(run)
	return _c
}

// reconcileDefaultBackendSet provides a mock function with given fields: ctx, params
func (_m *MockociLoadBalancerModel) reconcileDefaultBackendSet(ctx context.Context, params reconcileDefaultBackendParams) (loadbalancer.BackendSet, error) {
	ret := _m.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for reconcileDefaultBackendSet")
	}

	var r0 loadbalancer.BackendSet
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, reconcileDefaultBackendParams) (loadbalancer.BackendSet, error)); ok {
		return rf(ctx, params)
	}
	if rf, ok := ret.Get(0).(func(context.Context, reconcileDefaultBackendParams) loadbalancer.BackendSet); ok {
		r0 = rf(ctx, params)
	} else {
		r0 = ret.Get(0).(loadbalancer.BackendSet)
	}

	if rf, ok := ret.Get(1).(func(context.Context, reconcileDefaultBackendParams) error); ok {
		r1 = rf(ctx, params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockociLoadBalancerModel_reconcileDefaultBackendSet_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'reconcileDefaultBackendSet'
type MockociLoadBalancerModel_reconcileDefaultBackendSet_Call struct {
	*mock.Call
}

// reconcileDefaultBackendSet is a helper method to define mock.On call
//   - ctx context.Context
//   - params reconcileDefaultBackendParams
func (_e *MockociLoadBalancerModel_Expecter) reconcileDefaultBackendSet(ctx interface{}, params interface{}) *MockociLoadBalancerModel_reconcileDefaultBackendSet_Call {
	return &MockociLoadBalancerModel_reconcileDefaultBackendSet_Call{Call: _e.mock.On("reconcileDefaultBackendSet", ctx, params)}
}

func (_c *MockociLoadBalancerModel_reconcileDefaultBackendSet_Call) Run(run func(ctx context.Context, params reconcileDefaultBackendParams)) *MockociLoadBalancerModel_reconcileDefaultBackendSet_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(reconcileDefaultBackendParams))
	})
	return _c
}

func (_c *MockociLoadBalancerModel_reconcileDefaultBackendSet_Call) Return(_a0 loadbalancer.BackendSet, _a1 error) *MockociLoadBalancerModel_reconcileDefaultBackendSet_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockociLoadBalancerModel_reconcileDefaultBackendSet_Call) RunAndReturn(run func(context.Context, reconcileDefaultBackendParams) (loadbalancer.BackendSet, error)) *MockociLoadBalancerModel_reconcileDefaultBackendSet_Call {
	_c.Call.Return(run)
	return _c
}

// reconcileHTTPListener provides a mock function with given fields: ctx, params
func (_m *MockociLoadBalancerModel) reconcileHTTPListener(ctx context.Context, params reconcileHTTPListenerParams) error {
	ret := _m.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for reconcileHTTPListener")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, reconcileHTTPListenerParams) error); ok {
		r0 = rf(ctx, params)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockociLoadBalancerModel_reconcileHTTPListener_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'reconcileHTTPListener'
type MockociLoadBalancerModel_reconcileHTTPListener_Call struct {
	*mock.Call
}

// reconcileHTTPListener is a helper method to define mock.On call
//   - ctx context.Context
//   - params reconcileHTTPListenerParams
func (_e *MockociLoadBalancerModel_Expecter) reconcileHTTPListener(ctx interface{}, params interface{}) *MockociLoadBalancerModel_reconcileHTTPListener_Call {
	return &MockociLoadBalancerModel_reconcileHTTPListener_Call{Call: _e.mock.On("reconcileHTTPListener", ctx, params)}
}

func (_c *MockociLoadBalancerModel_reconcileHTTPListener_Call) Run(run func(ctx context.Context, params reconcileHTTPListenerParams)) *MockociLoadBalancerModel_reconcileHTTPListener_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(reconcileHTTPListenerParams))
	})
	return _c
}

func (_c *MockociLoadBalancerModel_reconcileHTTPListener_Call) Return(_a0 error) *MockociLoadBalancerModel_reconcileHTTPListener_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockociLoadBalancerModel_reconcileHTTPListener_Call) RunAndReturn(run func(context.Context, reconcileHTTPListenerParams) error) *MockociLoadBalancerModel_reconcileHTTPListener_Call {
	_c.Call.Return(run)
	return _c
}

// reconcileListenersCertificates provides a mock function with given fields: ctx, params
func (_m *MockociLoadBalancerModel) reconcileListenersCertificates(ctx context.Context, params reconcileListenersCertificatesParams) (reconcileListenersCertificatesResult, error) {
	ret := _m.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for reconcileListenersCertificates")
	}

	var r0 reconcileListenersCertificatesResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, reconcileListenersCertificatesParams) (reconcileListenersCertificatesResult, error)); ok {
		return rf(ctx, params)
	}
	if rf, ok := ret.Get(0).(func(context.Context, reconcileListenersCertificatesParams) reconcileListenersCertificatesResult); ok {
		r0 = rf(ctx, params)
	} else {
		r0 = ret.Get(0).(reconcileListenersCertificatesResult)
	}

	if rf, ok := ret.Get(1).(func(context.Context, reconcileListenersCertificatesParams) error); ok {
		r1 = rf(ctx, params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockociLoadBalancerModel_reconcileListenersCertificates_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'reconcileListenersCertificates'
type MockociLoadBalancerModel_reconcileListenersCertificates_Call struct {
	*mock.Call
}

// reconcileListenersCertificates is a helper method to define mock.On call
//   - ctx context.Context
//   - params reconcileListenersCertificatesParams
func (_e *MockociLoadBalancerModel_Expecter) reconcileListenersCertificates(ctx interface{}, params interface{}) *MockociLoadBalancerModel_reconcileListenersCertificates_Call {
	return &MockociLoadBalancerModel_reconcileListenersCertificates_Call{Call: _e.mock.On("reconcileListenersCertificates", ctx, params)}
}

func (_c *MockociLoadBalancerModel_reconcileListenersCertificates_Call) Run(run func(ctx context.Context, params reconcileListenersCertificatesParams)) *MockociLoadBalancerModel_reconcileListenersCertificates_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(reconcileListenersCertificatesParams))
	})
	return _c
}

func (_c *MockociLoadBalancerModel_reconcileListenersCertificates_Call) Return(_a0 reconcileListenersCertificatesResult, _a1 error) *MockociLoadBalancerModel_reconcileListenersCertificates_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockociLoadBalancerModel_reconcileListenersCertificates_Call) RunAndReturn(run func(context.Context, reconcileListenersCertificatesParams) (reconcileListenersCertificatesResult, error)) *MockociLoadBalancerModel_reconcileListenersCertificates_Call {
	_c.Call.Return(run)
	return _c
}

// removeMissingListeners provides a mock function with given fields: ctx, params
func (_m *MockociLoadBalancerModel) removeMissingListeners(ctx context.Context, params removeMissingListenersParams) error {
	ret := _m.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for removeMissingListeners")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, removeMissingListenersParams) error); ok {
		r0 = rf(ctx, params)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockociLoadBalancerModel_removeMissingListeners_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'removeMissingListeners'
type MockociLoadBalancerModel_removeMissingListeners_Call struct {
	*mock.Call
}

// removeMissingListeners is a helper method to define mock.On call
//   - ctx context.Context
//   - params removeMissingListenersParams
func (_e *MockociLoadBalancerModel_Expecter) removeMissingListeners(ctx interface{}, params interface{}) *MockociLoadBalancerModel_removeMissingListeners_Call {
	return &MockociLoadBalancerModel_removeMissingListeners_Call{Call: _e.mock.On("removeMissingListeners", ctx, params)}
}

func (_c *MockociLoadBalancerModel_removeMissingListeners_Call) Run(run func(ctx context.Context, params removeMissingListenersParams)) *MockociLoadBalancerModel_removeMissingListeners_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(removeMissingListenersParams))
	})
	return _c
}

func (_c *MockociLoadBalancerModel_removeMissingListeners_Call) Return(_a0 error) *MockociLoadBalancerModel_removeMissingListeners_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockociLoadBalancerModel_removeMissingListeners_Call) RunAndReturn(run func(context.Context, removeMissingListenersParams) error) *MockociLoadBalancerModel_removeMissingListeners_Call {
	_c.Call.Return(run)
	return _c
}

// removeUnusedCertificates provides a mock function with given fields: ctx, params
func (_m *MockociLoadBalancerModel) removeUnusedCertificates(ctx context.Context, params removeUnusedCertificatesParams) error {
	ret := _m.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for removeUnusedCertificates")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, removeUnusedCertificatesParams) error); ok {
		r0 = rf(ctx, params)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockociLoadBalancerModel_removeUnusedCertificates_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'removeUnusedCertificates'
type MockociLoadBalancerModel_removeUnusedCertificates_Call struct {
	*mock.Call
}

// removeUnusedCertificates is a helper method to define mock.On call
//   - ctx context.Context
//   - params removeUnusedCertificatesParams
func (_e *MockociLoadBalancerModel_Expecter) removeUnusedCertificates(ctx interface{}, params interface{}) *MockociLoadBalancerModel_removeUnusedCertificates_Call {
	return &MockociLoadBalancerModel_removeUnusedCertificates_Call{Call: _e.mock.On("removeUnusedCertificates", ctx, params)}
}

func (_c *MockociLoadBalancerModel_removeUnusedCertificates_Call) Run(run func(ctx context.Context, params removeUnusedCertificatesParams)) *MockociLoadBalancerModel_removeUnusedCertificates_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(removeUnusedCertificatesParams))
	})
	return _c
}

func (_c *MockociLoadBalancerModel_removeUnusedCertificates_Call) Return(_a0 error) *MockociLoadBalancerModel_removeUnusedCertificates_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockociLoadBalancerModel_removeUnusedCertificates_Call) RunAndReturn(run func(context.Context, removeUnusedCertificatesParams) error) *MockociLoadBalancerModel_removeUnusedCertificates_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockociLoadBalancerModel creates a new instance of MockociLoadBalancerModel. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockociLoadBalancerModel(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockociLoadBalancerModel {
	mock := &MockociLoadBalancerModel{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
