// Code generated by mockery. DO NOT EDIT.

//go:build !release

package app

import (
	mock "github.com/stretchr/testify/mock"
	v1 "sigs.k8s.io/gateway-api/apis/v1"
)

// MockociLoadBalancerRoutingRulesMapper is an autogenerated mock type for the ociLoadBalancerRoutingRulesMapper type
type MockociLoadBalancerRoutingRulesMapper struct {
	mock.Mock
}

type MockociLoadBalancerRoutingRulesMapper_Expecter struct {
	mock *mock.Mock
}

func (_m *MockociLoadBalancerRoutingRulesMapper) EXPECT() *MockociLoadBalancerRoutingRulesMapper_Expecter {
	return &MockociLoadBalancerRoutingRulesMapper_Expecter{mock: &_m.Mock}
}

// mapHTTPRouteMatchToCondition provides a mock function with given fields: match
func (_m *MockociLoadBalancerRoutingRulesMapper) mapHTTPRouteMatchToCondition(match v1.HTTPRouteMatch) (string, error) {
	ret := _m.Called(match)

	if len(ret) == 0 {
		panic("no return value specified for mapHTTPRouteMatchToCondition")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(v1.HTTPRouteMatch) (string, error)); ok {
		return rf(match)
	}
	if rf, ok := ret.Get(0).(func(v1.HTTPRouteMatch) string); ok {
		r0 = rf(match)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(v1.HTTPRouteMatch) error); ok {
		r1 = rf(match)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockociLoadBalancerRoutingRulesMapper_mapHTTPRouteMatchToCondition_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'mapHTTPRouteMatchToCondition'
type MockociLoadBalancerRoutingRulesMapper_mapHTTPRouteMatchToCondition_Call struct {
	*mock.Call
}

// mapHTTPRouteMatchToCondition is a helper method to define mock.On call
//   - match v1.HTTPRouteMatch
func (_e *MockociLoadBalancerRoutingRulesMapper_Expecter) mapHTTPRouteMatchToCondition(match interface{}) *MockociLoadBalancerRoutingRulesMapper_mapHTTPRouteMatchToCondition_Call {
	return &MockociLoadBalancerRoutingRulesMapper_mapHTTPRouteMatchToCondition_Call{Call: _e.mock.On("mapHTTPRouteMatchToCondition", match)}
}

func (_c *MockociLoadBalancerRoutingRulesMapper_mapHTTPRouteMatchToCondition_Call) Run(run func(match v1.HTTPRouteMatch)) *MockociLoadBalancerRoutingRulesMapper_mapHTTPRouteMatchToCondition_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(v1.HTTPRouteMatch))
	})
	return _c
}

func (_c *MockociLoadBalancerRoutingRulesMapper_mapHTTPRouteMatchToCondition_Call) Return(_a0 string, _a1 error) *MockociLoadBalancerRoutingRulesMapper_mapHTTPRouteMatchToCondition_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockociLoadBalancerRoutingRulesMapper_mapHTTPRouteMatchToCondition_Call) RunAndReturn(run func(v1.HTTPRouteMatch) (string, error)) *MockociLoadBalancerRoutingRulesMapper_mapHTTPRouteMatchToCondition_Call {
	_c.Call.Return(run)
	return _c
}

// mapHTTPRouteMatchesToCondition provides a mock function with given fields: matches
func (_m *MockociLoadBalancerRoutingRulesMapper) mapHTTPRouteMatchesToCondition(matches []v1.HTTPRouteMatch) (string, error) {
	ret := _m.Called(matches)

	if len(ret) == 0 {
		panic("no return value specified for mapHTTPRouteMatchesToCondition")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func([]v1.HTTPRouteMatch) (string, error)); ok {
		return rf(matches)
	}
	if rf, ok := ret.Get(0).(func([]v1.HTTPRouteMatch) string); ok {
		r0 = rf(matches)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func([]v1.HTTPRouteMatch) error); ok {
		r1 = rf(matches)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockociLoadBalancerRoutingRulesMapper_mapHTTPRouteMatchesToCondition_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'mapHTTPRouteMatchesToCondition'
type MockociLoadBalancerRoutingRulesMapper_mapHTTPRouteMatchesToCondition_Call struct {
	*mock.Call
}

// mapHTTPRouteMatchesToCondition is a helper method to define mock.On call
//   - matches []v1.HTTPRouteMatch
func (_e *MockociLoadBalancerRoutingRulesMapper_Expecter) mapHTTPRouteMatchesToCondition(matches interface{}) *MockociLoadBalancerRoutingRulesMapper_mapHTTPRouteMatchesToCondition_Call {
	return &MockociLoadBalancerRoutingRulesMapper_mapHTTPRouteMatchesToCondition_Call{Call: _e.mock.On("mapHTTPRouteMatchesToCondition", matches)}
}

func (_c *MockociLoadBalancerRoutingRulesMapper_mapHTTPRouteMatchesToCondition_Call) Run(run func(matches []v1.HTTPRouteMatch)) *MockociLoadBalancerRoutingRulesMapper_mapHTTPRouteMatchesToCondition_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].([]v1.HTTPRouteMatch))
	})
	return _c
}

func (_c *MockociLoadBalancerRoutingRulesMapper_mapHTTPRouteMatchesToCondition_Call) Return(_a0 string, _a1 error) *MockociLoadBalancerRoutingRulesMapper_mapHTTPRouteMatchesToCondition_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockociLoadBalancerRoutingRulesMapper_mapHTTPRouteMatchesToCondition_Call) RunAndReturn(run func([]v1.HTTPRouteMatch) (string, error)) *MockociLoadBalancerRoutingRulesMapper_mapHTTPRouteMatchesToCondition_Call {
	_c.Call.Return(run)
	return _c
}

// mapHTTPRouteHostnamesAndMatchesToCondition provides a mock function with given fields: hostnames, listenerPort, matches
func (_m *MockociLoadBalancerRoutingRulesMapper) mapHTTPRouteHostnamesAndMatchesToCondition(hostnames []v1.Hostname, listenerPort v1.PortNumber, matches []v1.HTTPRouteMatch) (string, error) {
	ret := _m.Called(hostnames, listenerPort, matches)

	if len(ret) == 0 {
		panic("no return value specified for mapHTTPRouteHostnamesAndMatchesToCondition")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func([]v1.Hostname, v1.PortNumber, []v1.HTTPRouteMatch) (string, error)); ok {
		return rf(hostnames, listenerPort, matches)
	}
	if rf, ok := ret.Get(0).(func([]v1.Hostname, v1.PortNumber, []v1.HTTPRouteMatch) string); ok {
		r0 = rf(hostnames, listenerPort, matches)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func([]v1.Hostname, v1.PortNumber, []v1.HTTPRouteMatch) error); ok {
		r1 = rf(hostnames, listenerPort, matches)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockociLoadBalancerRoutingRulesMapper_mapHTTPRouteHostnamesAndMatchesToCondition_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'mapHTTPRouteHostnamesAndMatchesToCondition'
type MockociLoadBalancerRoutingRulesMapper_mapHTTPRouteHostnamesAndMatchesToCondition_Call struct {
	*mock.Call
}

// mapHTTPRouteHostnamesAndMatchesToCondition is a helper method to define mock.On call
//   - hostnames []v1.Hostname
//   - listenerPort v1.PortNumber
//   - matches []v1.HTTPRouteMatch
func (_e *MockociLoadBalancerRoutingRulesMapper_Expecter) mapHTTPRouteHostnamesAndMatchesToCondition(hostnames interface{}, listenerPort interface{}, matches interface{}) *MockociLoadBalancerRoutingRulesMapper_mapHTTPRouteHostnamesAndMatchesToCondition_Call {
	return &MockociLoadBalancerRoutingRulesMapper_mapHTTPRouteHostnamesAndMatchesToCondition_Call{Call: _e.mock.On("mapHTTPRouteHostnamesAndMatchesToCondition", hostnames, listenerPort, matches)}
}

func (_c *MockociLoadBalancerRoutingRulesMapper_mapHTTPRouteHostnamesAndMatchesToCondition_Call) Run(run func(hostnames []v1.Hostname, listenerPort v1.PortNumber, matches []v1.HTTPRouteMatch)) *MockociLoadBalancerRoutingRulesMapper_mapHTTPRouteHostnamesAndMatchesToCondition_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].([]v1.Hostname), args[1].(v1.PortNumber), args[2].([]v1.HTTPRouteMatch))
	})
	return _c
}

func (_c *MockociLoadBalancerRoutingRulesMapper_mapHTTPRouteHostnamesAndMatchesToCondition_Call) Return(_a0 string, _a1 error) *MockociLoadBalancerRoutingRulesMapper_mapHTTPRouteHostnamesAndMatchesToCondition_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockociLoadBalancerRoutingRulesMapper_mapHTTPRouteHostnamesAndMatchesToCondition_Call) RunAndReturn(run func([]v1.Hostname, v1.PortNumber, []v1.HTTPRouteMatch) (string, error)) *MockociLoadBalancerRoutingRulesMapper_mapHTTPRouteHostnamesAndMatchesToCondition_Call {
	_c.Call.Return(run)
	return _c
}

// mapGRPCRouteHostnamesAndMatchesToCondition provides a mock function with given fields: hostnames, listenerPort, matches
func (_m *MockociLoadBalancerRoutingRulesMapper) mapGRPCRouteHostnamesAndMatchesToCondition(hostnames []v1.Hostname, listenerPort v1.PortNumber, matches []v1.GRPCRouteMatch) (string, error) {
	ret := _m.Called(hostnames, listenerPort, matches)

	if len(ret) == 0 {
		panic("no return value specified for mapGRPCRouteHostnamesAndMatchesToCondition")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func([]v1.Hostname, v1.PortNumber, []v1.GRPCRouteMatch) (string, error)); ok {
		return rf(hostnames, listenerPort, matches)
	}
	if rf, ok := ret.Get(0).(func([]v1.Hostname, v1.PortNumber, []v1.GRPCRouteMatch) string); ok {
		r0 = rf(hostnames, listenerPort, matches)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func([]v1.Hostname, v1.PortNumber, []v1.GRPCRouteMatch) error); ok {
		r1 = rf(hostnames, listenerPort, matches)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockociLoadBalancerRoutingRulesMapper_mapGRPCRouteHostnamesAndMatchesToCondition_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'mapGRPCRouteHostnamesAndMatchesToCondition'
type MockociLoadBalancerRoutingRulesMapper_mapGRPCRouteHostnamesAndMatchesToCondition_Call struct {
	*mock.Call
}

// mapGRPCRouteHostnamesAndMatchesToCondition is a helper method to define mock.On call
//   - hostnames []v1.Hostname
//   - listenerPort v1.PortNumber
//   - matches []v1.GRPCRouteMatch
func (_e *MockociLoadBalancerRoutingRulesMapper_Expecter) mapGRPCRouteHostnamesAndMatchesToCondition(hostnames interface{}, listenerPort interface{}, matches interface{}) *MockociLoadBalancerRoutingRulesMapper_mapGRPCRouteHostnamesAndMatchesToCondition_Call {
	return &MockociLoadBalancerRoutingRulesMapper_mapGRPCRouteHostnamesAndMatchesToCondition_Call{Call: _e.mock.On("mapGRPCRouteHostnamesAndMatchesToCondition", hostnames, listenerPort, matches)}
}

func (_c *MockociLoadBalancerRoutingRulesMapper_mapGRPCRouteHostnamesAndMatchesToCondition_Call) Run(run func(hostnames []v1.Hostname, listenerPort v1.PortNumber, matches []v1.GRPCRouteMatch)) *MockociLoadBalancerRoutingRulesMapper_mapGRPCRouteHostnamesAndMatchesToCondition_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].([]v1.Hostname), args[1].(v1.PortNumber), args[2].([]v1.GRPCRouteMatch))
	})
	return _c
}

func (_c *MockociLoadBalancerRoutingRulesMapper_mapGRPCRouteHostnamesAndMatchesToCondition_Call) Return(_a0 string, _a1 error) *MockociLoadBalancerRoutingRulesMapper_mapGRPCRouteHostnamesAndMatchesToCondition_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockociLoadBalancerRoutingRulesMapper_mapGRPCRouteHostnamesAndMatchesToCondition_Call) RunAndReturn(run func([]v1.Hostname, v1.PortNumber, []v1.GRPCRouteMatch) (string, error)) *MockociLoadBalancerRoutingRulesMapper_mapGRPCRouteHostnamesAndMatchesToCondition_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockociLoadBalancerRoutingRulesMapper creates a new instance of MockociLoadBalancerRoutingRulesMapper. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockociLoadBalancerRoutingRulesMapper(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockociLoadBalancerRoutingRulesMapper {
	mock := &MockociLoadBalancerRoutingRulesMapper{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
